apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage
  annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-9"